// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdfFfUghWoL5U-_VmPQM_DlLNc_SREgnA',
    appId: '1:679123839989:web:3d4b9ef7a807d211dc8ebc',
    messagingSenderId: '679123839989',
    projectId: 'fooddelivery-c333e',
    authDomain: 'fooddelivery-c333e.firebaseapp.com',
    storageBucket: 'fooddelivery-c333e.firebasestorage.app',
    measurementId: 'G-CW93YBE49V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANEX7CSMLNGpSQFOKXDuNeI4v8FzROlcU',
    appId: '1:679123839989:android:b56293eecb3554b6dc8ebc',
    messagingSenderId: '679123839989',
    projectId: 'fooddelivery-c333e',
    storageBucket: 'fooddelivery-c333e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdfFfUghWoL5U-_VmPQM_DlLNc_SREgnA',
    appId: '1:679123839989:web:c2ccb93a22dfe96cdc8ebc',
    messagingSenderId: '679123839989',
    projectId: 'fooddelivery-c333e',
    authDomain: 'fooddelivery-c333e.firebaseapp.com',
    storageBucket: 'fooddelivery-c333e.firebasestorage.app',
    measurementId: 'G-L7T9160S7X',
  );
}
